apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-service
  template:
    metadata:
      labels:
        app: todo-service
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z todo-db 5432; do echo waiting for todo-db; sleep 2; done;']
        - name: wait-for-redis
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z redis 6379; do echo waiting for redis; sleep 2; done;']
      containers:
        - name: todo-service
          image: todoservice:poc
          imagePullPolicy: Never
          ports:
            - containerPort: 3002
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:argusadmin@todo-db:5432/todo_db?schema=public"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: SERVICE_NAME
              value: "toDoService"
            - name: PORT
              value: "3002"
            - name: NODE_ENV
              value: "production"
            - name: FRONTEND_URL
              value: "http://localhost:5173"
            - name: JWT_PUBLIC_KEY_PATH
              value: "public.pem"
---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  selector:
    app: todo-service
  ports:
    - port: 3002
      targetPort: 3002
